FROM ubuntu:22.04 AS python_builder
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y build-essential gdb lcov pkg-config libbz2-dev \
libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev libncurses5-dev \
libreadline-dev libsqlite3-dev libssl-dev lzma lzma-dev tk-dev \
uuid-dev zlib1g-dev xz-utils tar

WORKDIR /build
ADD https://www.python.org/ftp/python/3.10.18/Python-3.10.18.tar.xz /build/Python-3.10.18.tar.xz
RUN tar -xf Python-3.10.18.tar.xz
WORKDIR /build/Python-3.10.18
RUN ./configure --enable-optimizations --prefix='/usr' && make

FROM trame_common_rootless
# Necessary to install tzdata. It will default to UTC.
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=python_builder /build/Python-3.10.18 /tmp/Python-3.10.18

RUN apt update && apt install -y build-essential 

RUN cd /tmp/Python-3.10.18 && \
make install && \
rm -rv /tmp/Python-3.10.18 && \
ln /bin/python3.10 /bin/python && \
ln /bin/pip3 /bin/pip

# Never use a cache directory for pip, both here in this Dockerfile
# and when we run the container.
ENV PIP_NO_CACHE_DIR=1


# Install and upgrade pip
RUN wget -q -O- https://bootstrap.pypa.io/get-pip.py | python3.10 && \
pip install -U pip

# Install setup dependencies
RUN pip install PyYAML wheel

# Copy the pip scripts into place
COPY scripts/pip/* /opt/trame/

# Set venv paths
ENV TRAME_VENV=/deploy/server/venv
ENV PV_VENV=$TRAME_VENV
ENV VTK_VENV=$TRAME_VENV
ENV TRAME_PYTHON=${PYTHON_VERSION}

USER trame-user
